// packages/next/src/components/AppHeader.tsx
import Link from "next/link";

export function AppHeader() {
  return (
    <header className="flex items-center justify-center h-12 border-b-2">
      <nav>
        <ul className="inline-flex gap-4 font-bold">
          <li>
            <Link href="/">Home</Link>
          </li>
          <li>
            <Link href="/about/">About</Link>
          </li>
        </ul>
      </nav>
    </header>
  );
}

// packages/nuxt/components/AppHeader.vue
<template>
  <header>
    <UContainer class="container">
      <nav>
        <ul>
          <li>
            <ULink
              to="/"
              active-class="text-primary"
              inactive-class="text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-200"
              >Home</ULink
            >
          </li>
          <li>
            <ULink
              to="/about/"
              active-class="text-primary"
              inactive-class="text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-200"
              >About</ULink
            >
          </li>
        </ul>
      </nav>
    </UContainer>
  </header>
</template>

<style lang="scss">
header {
  border-bottom: 1px solid;
  padding-block: 1rem;
}

ul {
  align-items: center;
  display: flex;
  gap: 1rem;
  justify-content: center;
}
</style>
